import React from 'react';
import { Download, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const ReportDownloadButton = ({ data, chartRefs = [], fileName = 'complaint-report' }) => {
  const downloadPDF = async () => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      let currentY = 20;

      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(59, 130, 246);
      pdf.text('EduTracker - Complaint Analysis Report', pageWidth / 2, currentY, { align: 'center' });
      
      currentY += 15;
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, currentY, { align: 'center' });
      
      currentY += 20;

      // Summary Statistics
      pdf.setFontSize(16);
      pdf.setTextColor(0, 0, 0);
      pdf.text('Summary Statistics', 20, currentY);
      currentY += 10;

      pdf.setFontSize(11);
      if (data.stats) {
        const stats = [
          `Total Complaints: ${data.stats.total}`,
          `Pending: ${data.stats.pending}`,
          `In Progress: ${data.stats.inProgress}`,
          `Resolved: ${data.stats.resolved}`,
          `Completed: ${data.stats.completed || 0}`,
          `Completion Rate: ${data.stats.total > 0 ? (((data.stats.resolved + (data.stats.completed || 0)) / data.stats.total) * 100).toFixed(1) : 0}%`
        ];

        stats.forEach(stat => {
          pdf.text(stat, 25, currentY);
          currentY += 7;
        });
      }

      currentY += 10;

      // Category Breakdown
      if (data.byCategory) {
        pdf.setFontSize(14);
        pdf.text('Complaints by Category', 20, currentY);
        currentY += 10;

        pdf.setFontSize(11);
        Object.entries(data.byCategory).forEach(([category, count]) => {
          pdf.text(`${category}: ${count}`, 25, currentY);
          currentY += 7;
        });
      }

      // Add charts if provided
      if (chartRefs.length > 0) {
        for (let i = 0; i < chartRefs.length; i++) {
          const chartRef = chartRefs[i];
          if (chartRef?.current) {
            try {
              const canvas = await html2canvas(chartRef.current, {
                backgroundColor: '#ffffff',
                scale: 2
              });
              
              const imgData = canvas.toDataURL('image/png');
              const imgWidth = pageWidth - 40;
              const imgHeight = (canvas.height * imgWidth) / canvas.width;

              // Add new page if needed
              if (currentY + imgHeight > pageHeight - 20) {
                pdf.addPage();
                currentY = 20;
              }

              pdf.addImage(imgData, 'PNG', 20, currentY, imgWidth, imgHeight);
              currentY += imgHeight + 10;
            } catch (error) {
              console.warn('Failed to capture chart:', error);
            }
          }
        }
      }

      // Footer
      const totalPages = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(128, 128, 128);
        pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        pdf.text('Generated by EduTracker System', pageWidth / 2, pageHeight - 5, { align: 'center' });
      }

      pdf.save(`${fileName}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF report. Please try again.');
    }
  };

  const downloadCSV = () => {
    try {
      let csvContent = 'Category,Count,Percentage\n';
      
      if (data.byCategory) {
        const total = Object.values(data.byCategory).reduce((sum, count) => sum + count, 0);
        Object.entries(data.byCategory).forEach(([category, count]) => {
          const percentage = total > 0 ? ((count / total) * 100).toFixed(1) : 0;
          csvContent += `${category},${count},${percentage}%\n`;
        });
      }

      csvContent += '\nStatus,Count\n';
      if (data.stats) {
        csvContent += `Pending,${data.stats.pending}\n`;
        csvContent += `In Progress,${data.stats.inProgress}\n`;
        csvContent += `Resolved,${data.stats.resolved}\n`;
        csvContent += `Completed,${data.stats.completed || 0}\n`;
      }

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `${fileName}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error generating CSV:', error);
      alert('Error generating CSV report. Please try again.');
    }
  };

  return (
    <div className="flex space-x-3">
      <button
        onClick={downloadPDF}
        className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors flex items-center space-x-2"
      >
        <Download className="h-4 w-4" />
        <span>Download PDF</span>
      </button>
      <button
        onClick={downloadCSV}
        className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors flex items-center space-x-2"
      >
        <FileText className="h-4 w-4" />
        <span>Download CSV</span>
      </button>
    </div>
  );
};

export default ReportDownloadButton;